### ISSUE TITLE
MS Feedback: Is the PositionObserver intended for Inline elements?

### ISSUE THREAD

**Issue by travisleithead** [slightlyoff/IntersectionObserver#10]
#### Is the PositionObserver intended for Inline elements?

Does the proposal anticipate PositionObserver usage on inline elements? We assume so, and in that case, are the quads supposed to mirror getClientRects()?

**Comment by ojanvafai** [comment]
Concluded to use the boundingClientRect for both the observed element and the viewport element, which makes the inlines no different from block. Duping against issue 13 since they're the same resolution now.

**Comment by ojanvafai** [comment]
issue #13 that is
