### ISSUE TITLE
MS Feedback: Define the callback rate (min/max?)

### ISSUE THREAD

**Issue by travisleithead** [slightlyoff/IntersectionObserver#11]
#### Define the callback rate (min/max?)
 
Rate of callback and time of callback should be more defined (or course). At least a rate limit would be nice (no more than 1 callback per 500 ms or some-such).

**Comment by ojanvafai** [comment]
A large rate limit would not work for the ads use-case. They need relatively low latency (on the order of 1-3 frames), for example, see page 7 of http://www.mediaratingcouncil.org/063014%20Viewable%20Ad%20Impression%20Guideline_Final.pdf. 

The spec we were going to propose is that any time the position of an observed element changes it queues a change record (but does not fire the callback) and it posts a task to drain the change records (if there isn't such a task posted already). When that task fires, it drains all the queued change records.

In the case of layout thrashing, we'd still only do one callback when the posted task fires. It also does not block the frame from painting (at least, not anymore than setTimeout(0) does).

In V1, authors could easily control the callback rate themselves by saving out the change records in the callback and queueing a handler themselves. In V2, if we find author demand for a callback rate, we could easily add such a thing to the PositionObserverOptions. Does that seem good enough or do you think V1 needs to allow configuring the callback rate?

**Comment by ojanvafai** [comment]
Resolved in Paris to post a task in issue 23.
