### ISSUE TITLE
Provide Microsoft Edge-team feedback on PositionObserver

### ISSUE THREAD

**Issue by travisleithead** [slightlyoff/IntersectionObserver#2]

**Comment by travisleithead** [comment]
I have our engineers reviewing my typed version of the feedback we generated at an internal review meeting. Hoping to get it finalized and posted tomorrow.

**Comment by travisleithead** [comment]
Some preliminaries:

> This is a sketch! We've tried to pattern the initial design  Object.observe()  and DOM's Mutation Observers. It's unclear if we should simply make this a special form of Mutation Observer.

I think this is a different enough scenario that it probably shouldn't be consider a kind of element "mutation".

> There's a question about occlusion: should we try to lean on computed opacity or should the API only ever report quads that have no occlusion/filtering/transforms of any kind?

We tended to think that the raw occlusion info should be provided for the author to decide. Not sure yet how to provide this data (bboxes, element refs?) 

> The specific timing of of change record delivery is also TBD.

Yep; would need some specific timing or time limit constraints.

> Is the magical top-level viewport too magical? What are the alternatives?

Not sure if I understand what is meant by this. We have a couple of viewports to consider, and then we have yet another implementation-specific rendering surface that is a bit larger than a viewport for scrolling/zooming/panning optimizations.

> Is it meaningful to have overdraw queries against the default viewport?

We didn't think the query format was going to be successful, but we did recognize that having a bit of viewport + extended region would be an important feature--doesn't have to be too complicated.

**Comment by travisleithead** [comment]
## Microsoft Feedback on [PositionObserver Proposal](https://github.com/slightlyoff/PositionObserver/blob/master/explainer.md)

## Summary

We all clearly understood (and have empathy for) the problem space that this proposal addresses (though we think some of the scenarios are reaching). We certainly see room to improve the state-of-the-art. Specific points of feedback are filed as separate issues--this represents the general feedback.

Honestly, tackling this problem is not our highest priority at the moment (we would not drop what we are planning in order to start working on this right away). We are sensitive to the problems with jank and related user-experience issues and are planning to address and minimize this, but from a quality-of-implementation standpoint (before prioritizing an API solution). Yet, to enable websites to start to address this problem on their own, we recognize that an API can be a great solution to start evangelizing.
 
At a high-level, the current proposal seems over-engineered. It appears to be catering to too many scenarios at once. We believe some of the aspects of the design will be difficult for average web devs to reason about. 

We also have questions about the proposed scenarios. Of the three target scenarios we object to this approach for one (data scrollers), question another (lazy loader), and are under-informed about the third (advertising impressions). We think there's an opportunity to get better agreement and mutual understanding of the scenarios we’re trying to solve before bike-shedding the details.

## Issue index:

* Feedback on the scenarios: #3, #5, #6
* Specific proposal feedback: #7, #8, #9, #10, #11
* Alternative idea: #4

Thanks!
-Travis on behalf of the MS Edge Platform Team

**Comment by ojanvafai** [comment]
I believe we've addressed all the MS feedback on comments and in person in Paris except for issue 10. Closing this for now. Please reopen if I missed anything.
