### ISSUE TITLE
viewportmodifier should allow negative values

### ISSUE THREAD

**Issue by ojanvafai** [slightlyoff/IntersectionObserver#27]
There are use-cases for doing things when an element crosses a threshold inside a scroller.

**Comment by ojanvafai** [comment]
Like margin, can have multiple values for each edge and or a single value for all of them.

**Comment by esprehn** [comment]
Added a comment about this:
https://github.com/slightlyoff/PositionObserver/commit/9660cee0d5db1b8881c280eb4673e4a63be665f0
