### ISSUE TITLE
MS Feedback: Data scrollers (List view) scenario likely not in scope

### ISSUE THREAD

**Issue by travisleithead** [slightlyoff/IntersectionObserver#3]
#### Data scrollers (List view) scenario likely not in scope

The list view scenario is not fully covered. In Microsoft's first version of the WinJS virtualized list view, we had an implementation similar to the one that this proposal tries to help facilitate. However, our experience with the v1 showed that frequent element cycling/thrashing led to terrible perf (in all UAs). Now in our v2+ we preload a larger subset of elements to avoid too frequence cycling, and this works better for avoiding the flashes of white and DOM thrashing as well.
 
There's a lot of code in our virtual list view for maintaining the virtual content length (for accurate scrollbar calculation). This is tightly coupled with addition/removal of virtual contents and is not really addressed by the proposal.
 
In the virtual list view case, there's usually not one specific element target which is the basis for determining when and how to hydrate/de-hydrate elements. To that end, the PositionObserver does not provide a direct solution here (though it might be useful indirectly by way of extending an element target's rectangle).
 
In general, we don't think the virtual list view scenario is/should be a target scenario for the feature. Its implementation is rather complicated and not likely fully addressed by PositionObserver.

**Comment by slightlyoff** [comment]
Hey Travis!

I think perhaps the example code doesn't serve as a good example of the architecture I was trying to go for there: my goal was *exactly* the sort of element recycling strategy you not that WinJS adopted in subsequent revisions (and which our high-performing Closure/Polymer UIs use). Generating new nodes each time doesn't scale.

My goal here was to show how this API can be used to improve the positioning calculations that the recycler/controller is going to be doing.

Does that clarify it?

**Comment by ojanvafai** [comment]
Also, Travis, can you clarify what you mean by "In the virtual list view case, there's usually not one specific element target which is the basis for determining when and how to hydrate/de-hydrate elements."?

**Comment by ojanvafai** [comment]
Closing issue. Please reopen if the comments don't address the concerns. Discussion with Matt, et al in Paris implied to me that MS is happy moving forward with the API modulo working out minor issues.
