### ISSUE TITLE
Clicking on "Element" goes to a javadoc, not the DOM spec

### ISSUE THREAD

**Issue by domenic** [slightlyoff/IntersectionObserver#30]
E.g. in https://rawgit.com/slightlyoff/IntersectionObserver/master/index.html#element-has 3.1.3 step 2.

**Comment by mpb** [comment]
Try  https://rawgit.com/slightlyoff/IntersectionObserver/master/index.bikeshed.html
Not fully converted over yet, but the links should be more standard there.

**Comment by mpb** [comment]
https://rawgit.com/slightlyoff/IntersectionObserver/master/index.bikeshed.html#3-1-2-element

**Comment by domenic** [comment]
Oh, dammit, I've been reviewing the wrong spec this whole time! :P.

Cool. I'll leave it up to you whether you want to close this or leave it until the cutover to Bikeshed.

**Comment by mpb** [comment]
Sorry about that!
I think the bikeshed version is as good if not better than the respec version now. I'll make that the primary, and resolve this one.

**Comment by mpb** [comment]
Closed via #40
