### ISSUE TITLE
IntersectionObserver's second argument must be optional

### ISSUE THREAD

**Issue by domenic** [slightlyoff/IntersectionObserver#31]
It is currently

```
Constructor(IntersectionObserverCallback callback, IntersectionObserverInit options)
```

It must instead be

```
Constructor(IntersectionObserverCallback callback, optional IntersectionObserverInit options)
```

[Per Web IDL](https://heycam.github.io/webidl/#dfn-optional-argument-default-value):

> If the type of an argument is a dictionary type or a union type that has a dictionary type as one of its flattened member types, and that dictionary type and its ancestors have no required members, and the argument is either the final argument or is followed only by optional arguments, then the argument MUST be specified as optional

**Comment by mpb** [comment]
Taken care of in pull #40.
