### ISSUE TITLE
DOMRectReadOnly is probably more appropriate than DOMRect

### ISSUE THREAD

**Issue by domenic** [slightlyoff/IntersectionObserver#32]
`readonly DOMRect rootBounds` means that `entry.rootBounds = {}` fails; `readonly DOMRectReadOnly rootBounds` means that `entry.rootBounds.x = -1` fails. Unless there are sensible semantics for allowing changes to the rects, it seems better to make them DOMRectReadOnlys.

**Comment by mpb** [comment]
Closed via #44

**Comment by ojanvafai** [comment]
I don't understand this. Why is it better to be readonly?

**Comment by domenic** [comment]
Why add a setter that does nothing useful? Mutating it doesn't change the rootBounds that were observed in the entry.

**Comment by ojanvafai** [comment]
It seems reasonable to me to save these rects off and do things with them
later. We just don't gain anything by making them readonly, do we?

**Comment by domenic** [comment]
We don't gain anything by adding a setter, do we?

Making them readonly seems to reflect the semantics better.

**Comment by ojanvafai** [comment]
I guess this matches MutationObserver too, so nevermind.
