### ISSUE TITLE
Use of dot notation is a bit confusing

### ISSUE THREAD

**Issue by domenic** [slightlyoff/IntersectionObserver#34]
E.g. talking about "_Document_.pendingCallbacks". I appreciate the efforts at precision to talk precisely about what internal slots each object has. In new specs that define their own objects I suggest notation like "_Document_@[[pendingCallbacks]]" and explicit discussion of internal slots.

For this case though, since you are extending objects defined in other specs which don't use those concepts, the use of dot notation is confusing. It is easy to think you are talking about normal JavaScript property access.

I'd suggest just going with ye olde "_Document_'s pendingCallbacks".

**Comment by domenic** [comment]
Taken care of in Bikeshed version.

**Comment by mpb** [comment]
Closed via #40.
