### ISSUE TITLE
Use of undefined variable "Document" throughout

### ISSUE THREAD

**Issue by domenic** [slightlyoff/IntersectionObserver#35]
All the processing model algorithms make reference to _Document_. But this is not defined. I assume it's meant to be a Document of some sort. But which one? From which window? This can be especially bad when e.g. code in one frame uses the IntersectionObserver constructor from another frame to observe an Element from a third frame.

**Comment by mpb** [comment]
I see the confusion. Is there standard terminology for this (something in DOM4 maybe?)

**Comment by domenic** [comment]
Well, first you have to pick the semantics you want. In that scenario, which of the three documents is appropriate? Maybe the current setup involves too much global state, and storing things on elements instead of on documents would be better? I notice MutationObserver does not do so much global state. Maybe following that model would work out better?

Once you've figured that out, there are standard ways of referring to the given documents. [Node document](https://dom.spec.whatwg.org/#concept-node-document) for the document that is the owner of a given node. [Entry settings object](https://html.spec.whatwg.org/#entry-settings-object)'s [responsible document](https://html.spec.whatwg.org/#responsible-document) for the document of the top-level script doing the work. [Incumbent settings object](https://html.spec.whatwg.org/#incumbent-settings-object)'s responsible document for the document of the script closest to the call site. (See also https://github.com/whatwg/html/issues/155.) And I could cook something up to correspond to the IntersectionObserver constructor's document too...
