### ISSUE TITLE
Why the slight differences from MutationObserver?

### ISSUE THREAD

**Issue by domenic** [slightlyoff/IntersectionObserver#37]
There are a number of slight differences in design from MutationObserver:

- IntersectionObserverInit is in the constructor, whereas for MutationObserver it is in the observe method.
- IntersectionObserver has an unobserve() method; MutationObserver does not.

These changes are probably well-motivated, but since I'm not too familiar with the design space, I find the mismatch surprising. If they are intentional, it would be nice to add a non-normative note explaining them. It might be the case that MutationObserver has flaws and this is a slightly better iteration.

**Comment by mpb** [comment]
MutationObserver always intended to go back and add ```unobserve```, but there hasn't been a real push for it yet.
For MutationObserver, each ```Node``` being observed could have a different set of attributes to filter. For IntersectionObserver, it seems to introduce more complication to have a different ```threshold```, ```root``` and ```rootMargin``` for each ```target```. without solving any use cases. A per-```observe``` init could be provided some time in the future without really impacting backwards compatibility, if V2 introduces a need for it.
Thoughts?

**Comment by mpb** [comment]
(Also, the use-case for IntersectionObserver's ```unobserve``` is for lazy-loaded elements. Once they are loaded, you don't really care about tracking them anymore. But it's a little heavy-weight to disconnect everything you are observing, and re-observe the ones you are still interested in. It would also be more overhead for the UA if you were pushed to create individial IntersectionObservers for each ```target```.)

**Comment by domenic** [comment]
Those sound like pretty good reasons! Thanks for explaining. A note in the spec along those lines would make sense to me.

**Comment by mpb** [comment]
PTAL at #46 for notes explaining these differences. Thanks!
