### ISSUE TITLE
MS Feedback: Alternative Idea: imperative and event-based

### ISSUE THREAD

**Issue by travisleithead** [slightlyoff/IntersectionObserver#4]
#### Alternative Idea: imperative and event-based
 
While we think the modeling of this feature on the MutationObserver pattern is good and familiar, we do wonder if a far-simpler design could be used to address the ad case. We see two common questions:

1. Set me up to respond when I'm visible (for some definition of this) -- the current approach
2. Tell me right now (or really soon) if I'm visible (I don't want to wait till later.) - an imperative approach.
 
The key aspects to preserve are:
* async
* can collect, consolidate, and service multiple requests at once.
 
In our quick brainstorm, the simplest solution was an event (e.g., "isvisible") that is fired to the element in question and carries some data about it's occlusion state (fully, partially, rect list...?). The occlusion state could be accurate enough for author code to determine percentage visibility, and/or what other elements are above it in stacking context (e.g., something like ```elementsFromPoint```, but for a rectangle... ```elementsFromRect```?).
 
We also think a Promise-based isVisible() or some-such will be a strongly-requested feature.
 
We think a simple way of extending the target/viewport dimensions is also useful.

**Comment by slightlyoff** [comment]
Hey Travis,

So there's a few things going on here; first, using events implies cancelation, which might have impacts on scrolling. We'd like to avoid creating more surface area that can do this in an API that doesn't require it. Next, is Promise delivery timing what you want for this? The issue there is that it's hard to batch the records and sift through them efficiently. Lastly, we'd like to avoid doing expensive work at a poor time for the system (i.e., should we allow something that asks our compositor for information at any point?) so the current design lets the system generate it and provide it at a (very small) delay within the processing pipeline (as opposed to outside of it).

How does this related to Edge's architecture for calculating these sorts of occlusion decisions? What does your pipeline look like?

**Comment by esprehn** [comment]
We also believe that configuration, ex. extending the viewport by distance or time, or changing how spammy the notifications are (threshold events) is important to address the use cases and allow authors to build performant apps. There's no precedent for configuring when and how events fire like this, PositionObserver allows us to specify these options like MutationObserver does.

**Comment by ojanvafai** [comment]
Closing issue. Please reopen if the comments don't address the concerns. Discussion with Matt, et al in Paris implied to me that MS is happy moving forward with the API modulo working out minor issues.
