### ISSUE TITLE
Add a link to the spec to the GitHub repo

### ISSUE THREAD

**Issue by domenic** [slightlyoff/IntersectionObserver#41]
I found https://rawgit.com/slightlyoff/IntersectionObserver/master/index.html on blink-dev but I can't find it from the readme.

Bonus points: make it the repo's website. (See e.g. the headline at https://github.com/whatwg/html at the top of the page.) I think only @slightlyoff can do that though.

**Comment by mpb** [comment]
I updated the readme. to @slightlyoff to either close or update further, thanks.
