### ISSUE TITLE
[[RegisteredIntersectionObservers]] setup is broken

### ISSUE THREAD

**Issue by domenic** [slightlyoff/IntersectionObserver#43]
This might be related to #35.

[[RegisteredIntersectionObservers]] is defined on Document and used in https://rawgit.com/slightlyoff/IntersectionObserver/master/index.html#3-3-event-loop, but nobody ever adds to it or removes from it.

In contrast, another [[RegisteredIntersectionObservers]] is defined on Element and modified by IntersectionObserver's methods, but nobody ever reads from it.

Again it might be worth consulting what Mutation Observers do here.

**Comment by domenic** [comment]
Note: I am pretty sure there is no need to do the compound microtask business that mutation observer does; queuing a task is fine. But consulting the data structure and where things are stored seems prudent.

**Comment by mpb** [comment]
IntersectionObserver intentionally *doesn't* want to mimic MutationObserver's microtasks. One of the intentions of IntersectionObserver is that it can run asynchronously and allow the user agent to deliver the events at a time less likely to affect the page. 

I can drop the [[RegisteredIntersectionObservers]] is from Document if I say Document has to iterate over all of its Elements, and for each element, iterate over the  [[RegisteredIntersectionObservers]]. I think it's probably going to work out better from an implementation standpoint to have the shortcut that Document tracks registered observers too.. does it make sense to update the processing steps to include keeping that up to date, or let each UA define it for themselves?

**Comment by domenic** [comment]
How MutationObserver does it is store a list of MutationObserver objects on each unit of related similar-origin browsing contexts. The mutation records are then stored on the MutationObserver objects themselves, and the event loop iterates over all MutationObserver objects and dispatches the records. Note how the queue is also kept individually on each MutationObserver, instead of using [[PendingIntersectionObserverCallbacks]] on document. A similar setup seems workable here, and I believe observably equivalent to your current setup.

But yeah, if that's not preferable, then iterating over all elements seems reasonable. Any implementation-specific caches don't need to be specced if they are not observable.

/cc @annevk in case he has any opinions.

**Comment by annevk** [comment]
I think it would be better not to have non-observable optimization paths in the specification other than non-normative notes.
