### ISSUE TITLE
MS Feedback: Delay loading scenario applicability questioned

### ISSUE THREAD

**Issue by travisleithead** [slightlyoff/IntersectionObserver#5]
#### Delay loading scenario applicability questioned

We're both critical of this scenario and supportive of it. We've definitely seen lazy image loaders be a scenario that authors could consider solving with PositionObserver (versus their current approach of spamming scroll events). In our rough brainstorm, we came up with a much more direct solution to solving this problem that doesn't need all the PositionObserver machinery as only a simple notice is needed just before the node would come into view. See Alternative Ideas in #4 applied to ```<img>``` elements.

**Comment by esprehn** [comment]
We observe that this is more than just ``<img>`` elements, it's usually "cards" like tumblr, or large page sections like disqus/fb comments/galleries and other big sections of media websites.

Using a single PositionObserver and a simple library you can observe each of the big sections on the page having generated them to take up some space in the page but be empty. As each section nears the viewport you can then load them.

##### Example

Authors include a lazyload JS library that adds a single PositionObserver to the page and calls observe() on every element that has the ``lazyload`` attribute.

```js
lazyload.register("comments", function(element) {
  // load the comments here. This is called when the comments element
  // nears the viewport.
});
```

They then annotate sections of the page with the attribute and the callback name. When the element becomes visible the callback will run and inflate that part of the page.

```html
<div lazyload="comments" style="height: 500px"></div>
```

Authors are already doing this today, but poorly using scroll listeners or raf polling.

**Comment by ojanvafai** [comment]
Closing issue. Please reopen the concerns are not address by the followup comments.
