### ISSUE TITLE
The requirement for target to be a descendant of [[root]] seems to ignore mutations

### ISSUE THREAD

**Issue by bzbarsky** [slightlyoff/IntersectionObserver#50]
`observe()` requires _target_ to be a descendant of `[[root]]` and the processing model in http://rawgit.com/slightlyoff/IntersectionObserver/master/index.html#3-3-event-loop assumes that the _target_ is a descendant of `[[root]]` but nothing enforces that the ancestors of _target_ don't change between the `observe()` call and the event loop processing.

**Comment by mpb** [comment]
Hm, the ```remove steps``` don't trigger in that situation? Is there another hook for ```reparent``` or something similar?

**Comment by bzbarsky** [comment]
What `remove steps` are you talking about?  There's nothing like that in http://rawgit.com/slightlyoff/IntersectionObserver/master/index.html that I can see.

**Comment by mpb** [comment]
Pull #47 involved some changes to the processing model. It landed a couple minutes ago, and now includes a reference to https://dom.spec.whatwg.org/#concept-node-remove-ext

**Comment by bzbarsky** [comment]
Ah, I see.  The DOM concept-node-remove-ext takes 3 arguments.  http://rawgit.com/slightlyoff/IntersectionObserver/master/index.html#removing-steps seems to assume only one argument.

Also, it should be clear that it's invoking the canonical `unobserve` method, not just doing `.unobserve()`, right?

With those fixed, I think we'll be good on this issue.

**Comment by domenic** [comment]
> Also, it should be clear that it's invoking the canonical unobserve method, not just doing .unobserve(), right?

I'll open a separate issue for that; noticed it in a couple of places.

**Comment by mpb** [comment]
Updated the unobserve algorithm vs calling .unobserve() issue in #67.
