### ISSUE TITLE
Definition of `IntersectionObserverEntry.time` needs to say what the zero time is

### ISSUE THREAD

**Issue by bzbarsky** [slightlyoff/IntersectionObserver#51]
Unfortunately, `DomHighResTimeStamp` doesn't have a well-defined zero time (thank you, web perf working group), so whenever you use it you have to say what your zero time is...  You probably want the navigationStart of something, but please coordinate with the webperf people for the right way to phrase this, especially in cases when a single `Window` has multiple `Document`s or vice versa.

**Comment by igrigorik** [comment]
@bzbarsky is the [current definition of time origin in HR-Time](https://w3c.github.io/hr-time/#time-origin-1) not sufficient? I was under the impression that we've resolved this.

**Comment by domenic** [comment]
AHAH! I knew there was a hidden ED of HR Time, and we wouldn't be forced to use a TR link...

**Comment by bzbarsky** [comment]
@igrigorik That definition works fine as long as this spec says which global it wants to use, yes.

**Comment by ojanvafai** [comment]
OK, so it seems we just need to point to the time origin in the HR-Time spec. 

@tabatkins says We should say "It's equal to the amount of time since the time origin of the window associated with the IntersectionObserver." with a link to https://w3c.github.io/hr-time/#time-origin-1.

@mpb @szager-chromium

**Comment by bzbarsky** [comment]
> OK, so it seems we just need to point to the time origin in the HR-Time spec. 

Yes, in that you need to say your DOMHighResTimeStamp measures time since the time origin, and which global's time origin is involved.  @tabatkins's suggestion sounds good to me, as long as something defines which window is associated with the IntersectionObserver.
