### ISSUE TITLE
Need to define handling of relative units for `threshold`

### ISSUE THREAD

**Issue by bzbarsky** [slightlyoff/IntersectionObserver#53]
Specifically, need to define what all the relative units are relative to: which viewports, which font-sizes, etc.

**Comment by mpb** [comment]
My vote would be for threshold to allow px or %s only.

**Comment by bzbarsky** [comment]
Note that right now it does not allow %, by the way, since it's defined to be https://drafts.csswg.org/css-values-3/#length-value

**Comment by mpb** [comment]
Is there a better value to use, or is it better to just enumerate that it can either be a straight pixel count, or a % of the total area of the element's boundingClientRect?

**Comment by bzbarsky** [comment]
I haven't thought enough through the use cases to have an answer for that question.

**Comment by tabatkins** [comment]
I'm still not sure what it actually means.  The text suggests it's an area, but the grammar says it's a length. Which is it?

**Comment by mpb** [comment]
Area.
I didn't know the unit of measurement for areas.

**Comment by tabatkins** [comment]
That's because there isn't one. ^_^  CSS hasn't had to deal with areas before.

What use-cases are we handling?  Is % plus some value for "any at all" okay?

**Comment by mpb** [comment]
That covers the use cases I know of (30%, 50%, 80%, 100% and 'non-zero
which may be < 1%')
My thought was actual pixel #s would let the developer specify what they
had in mind, and % could be an easy shorthand.
Are there any other specs that have something similar?

**Comment by ojanvafai** [comment]
Lets only allow % for now. I can't think of any non-percent use-cases and we can always add more allowed types in the future. I don't think we need "any at all" since we can define 0% appropriately so that any non-zero overlap counts.

**Comment by tabatkins** [comment]
> My thought was actual pixel #s would let the developer specify what they had in mind, and % could be an easy shorthand.

What could they possibly have in mind, though?  I'm just not able to imagine any case where I actually want to know "this many pixels are visible".  (Particularly given the troublesome definition of "pixel" in context - presumably it would be square CSS px, or you'd get radically different answers when using responsible images.)

@ojanvafai Yeah, I'm fine with letting 0% actually mean "anything greater than 0", since there's no use-case for an actual 0 value, and it avoids the "open ranges" problem nicely ([via behavior 3](https://wiki.csswg.org/spec/limited-ranges)).

**Comment by ojanvafai** [comment]
Said this on pull request 60 as well, but for good measure I'll add it here. Now that we're only supporting percentages we can simplify this a bunch.

I talked this over with @tabatkins and @shans about this and they convinced me that we should just take numbers in the [0-1] range. So, 5% would be 0.05 instead and we can just use numbers without any need to do parsing. To allow multiple we can make it allow " or sequence".

**Comment by mpb** [comment]
Addressed in #60
