### ISSUE TITLE
Queueing intersection observer tasks is pretty underdefined

### ISSUE THREAD

**Issue by bzbarsky** [slightlyoff/IntersectionObserver#54]
It looks like the UA is allowed to post a task or to post an idle request callback.  Those have quite different observable behavior and it wouldn't surprise me if pages came to depend on one or the other in practice, leading them to work in some UAs but not others.

We should just pick a behavior here and define it, in my opinion.

**Comment by ojanvafai** [comment]
We want more real world experience before picking. I suppose we could just pick a behavior now and change it later if we decide on something better that doesn't break content?

**Comment by bzbarsky** [comment]
I think in that case it's best to clearly say in the spec that a behavior will be picked before the spec is finalized and that for now UAs should experiment, so it's clear to everyone that the current state of things won't last.

**Comment by ojanvafai** [comment]
That makes sense. Will change soon.

**Comment by ojanvafai** [comment]
For now we'll say to queue an idle task with a deadline of 100ms, but we'll add an issue saying that we should consider making it just post a task instead.

**Comment by mpb** [comment]
Updated language in #71.
