### ISSUE TITLE
Support multiple observers on a single target Element

### ISSUE THREAD

**Issue by szager-chromium** [slightlyoff/IntersectionObserver#57]
The spec provides for a single PreviousIntersectionRect per target Element, which does not allow for multiple observers on a single target Element.

Proposal: RegisteredIntersectionObservers on the targetElement should be a sequence of:

{
    'observer': instance of IntersectionObserver,
    'previousVisibleRatio': ratio
}

**Comment by mpb** [comment]
#60 reduces the need for this, but we should still update to support multiple observers on one target.

**Comment by mpb** [comment]
Added some language which will hopefully address this.
