### ISSUE TITLE
MS Feedback: Usage for Ad Impression Usage Scenario (what is importance for into/out-of view)?

### ISSUE THREAD

**Issue by travisleithead** [slightlyoff/IntersectionObserver#6]
#### Usage for Ad Impression Usage Scenario (what is importance for into/out-of view)?

Occlusion seems pretty important (for ad impression accuracy). We think that occlusion should somehow be addressed in the solution.
 
Are the percent-in-view requirements really important? E.g., is this a deal-breaker for ad-impression tracking?
 
How do the quads relate to the trip-wire for what is considered in threshold? Is it the bounding box? Does this meet the accuracy requirements?

We assume various applied element transformations should be covered, as they are frequently used in advertising attention-grabbing strategies:

* CSS animations (in flight) (often used in the image carosel scenario)
* CSS transforms (incl. preserve-3d, rotations with no backface-visibility, etc.)
* SVG elements (polylines--these are to be bounding boxes?)
* elements whose DOM manipulation suddenly puts them in view (w/no scrolling)

**Comment by ojanvafai** [comment]
Occlusion is important. But it is an arms race against spammers, e.g. does it count as occluded if the overlay is 0.01 opacity? The rules of what ad networks will want will change over time. I think we *may* want to target occlusion, but will need to do so when there's more clear standards in the ads community.

V1 of this API is not targeted at malicious content. It's for non-malicious viewability (e.g. ads that haven't been scrolled into view). This is what we see the ad networks doing in practice today. So, we think getting a V1 out there that's focused on viewability, while leaving open the possibility of dealing with occlusion in a V2 API is the best path here. That sound OK?

Different ad groups are espousing different, frequently changing metrics here, so we don't want to bake an isVisible metric into the browser. But, an example of the sort of requirements we've heard is ">50% of the ad visible for >1 second", e.g. http://www.mediaratingcouncil.org/063014%20Viewable%20Ad%20Impression%20Guideline_Final.pdf.

In all of these cases though, it should work in the examples you list, but it's OK for the API to be async. I think bounding box is sufficient given that we're not worrying about malicious authors.

**Comment by ojanvafai** [comment]
Whoops. This was the link I intended to include for an example of the requirements. 
http://www.iab.net/viewability/faq#viewabilitythreshold

**Comment by ojanvafai** [comment]
Closing issue. Please reopen if my previous comment does not address the concerns.
