### ISSUE TITLE
The observer object is passed twice to callbacks

### ISSUE THREAD

**Issue by szager-chromium** [slightlyoff/IntersectionObserver#61]
In section 3.2.2:

"Invoke callback with queue as the first argument and observer as the second argument and callback this value."

The observer is passed as 'this', and (redundantly) as the second argument.

**Comment by mpb** [comment]
Inherited directly from Mutation Observer..

http://www.w3.org/TR/dom/#mutation-observers

>If queue is non-empty, call mo's callback with queue as first argument, and mo (itself) as second argument and callback this value. If this throws an exception, report the exception.
