### ISSUE TITLE
IntersectionObserver needs accessors for the IntersectionObserverInit values with which it was constructed

### ISSUE THREAD

**Issue by szager-chromium** [slightlyoff/IntersectionObserver#63]
root()
rootMargin()
threshold()

**Comment by szager-chromium** [comment]
To clarify why I think this is necessary: IntersectionObserverCallback is passed rootBounds, but not the root element.  It should be possible to get access to the root element without binding it to the callback when the observer is created.

**Comment by ojanvafai** [comment]
Readonly.

**Comment by mpb** [comment]
Addressed in pull #71
