### ISSUE TITLE
MS Feedback: viewportModifier calc magic too tricky

### ISSUE THREAD

**Issue by travisleithead** [slightlyoff/IntersectionObserver#7]
#### viewportModifier calc magic too tricky

Attempting to evaluate velocity and projected visibility of the target in terms of time seems exceptionally error-prone, hard to get interop, hard to test, etc. There is a clear desire to want an extended viewport dimension, and it seems much easer to go with something simple here (an extended border dimension, in pixels, for example would do fine--if you need more lead time, make the border bigger).

**Comment by slightlyoff** [comment]
We agree it isn't great! In particular, `calc` isn't workable. There are 2 distinct approaches: time and distance. Some engineers on the Chrome team feel strongly that this should be time based; it sounds like @rocallahan agrees?

We can imagine a world where you have 2 properties, one for time and one for dimension, but perhaps we should agree for a V1 which we'd do first.

Thoughts?

**Comment by rocallahan** [comment]
>  it sounds like @rocallahan agrees?

Correct.

**Comment by ojanvafai** [comment]
Decided in Paris to only ship the dimension one to start with.
