### ISSUE TITLE
intersectionObserver.observe() edge cases

### ISSUE THREAD

**Issue by zetafunction** [slightlyoff/IntersectionObserver#78]
1. What should happen if a page attempts to observe `null`? I'm guessing this probably just Won't Work, from a simple test in the console:
   ```  
   > document.body.removeChild(null)
   VM711:2 Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.(…)
   > document.body.appendChild(null)
   VM712:2 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.(…)
   ```  
   So maybe this doesn't need to be explicitly addressed in the spec.

2. A more interesting case is what should happen in the case of self-observation: in that case, the observer would fire all the time...

**Comment by szager-chromium** [comment]
1. Correct, the glue layer will prevent a null value for the target.

2. Self-observation is not allowed.  But as a thought experiment, I would expect a self-observation to fire exactly once, and then never fire again.
