### ISSUE TITLE
ETA

### ISSUE THREAD

**Issue by blasten** [slightlyoff/IntersectionObserver#80]
Is there an ETA to land `IntersectionObserver` in Canary? I'd love to try it out.

**Comment by szager-chromium** [comment]
It landed in trunk just a few days ago, it should already be in canary on
Windows and Mac, and it should be in dev branch some time next week.  To
use it, go to about:flags and turn on "Experimental Web Platform
features".  This page has some sample code under "Element Visibility":

https://github.com/slightlyoff/IntersectionObserver/blob/master/explainer.md

Feedback is desired!

**Comment by blasten** [comment]
@szager-chromium That is great news! We need to build an element that runs some logic on the scroll event to detect if the user reached a `scrollTop` threshold. I will try `IntersectionObserver` and provide some feedback!
